begin;

select plan(24);

select has_table('public', 'profiles', 'the application profile anchor exists');

select columns_are(
  'public',
  'profiles',
  array['id', 'created_at', 'display_name', 'bio', 'updated_at'],
  'the profile anchor includes only the settled basic scalar fields'
);

select col_type_is('public', 'profiles', 'id', 'uuid', 'profile identifiers are UUIDs');

select col_not_null('public', 'profiles', 'id', 'profile identifiers are required');

select col_is_pk('public', 'profiles', 'id', 'the Auth UUID is the profile primary key');

select col_type_is(
  'public',
  'profiles',
  'created_at',
  'timestamp with time zone',
  'profile creation time is timezone-aware'
);

select col_not_null(
  'public',
  'profiles',
  'created_at',
  'profile creation time is required'
);

select is(
  (
    select pg_get_expr(d.adbin, d.adrelid)
    from pg_attrdef as d
    join pg_attribute as a
      on a.attrelid = d.adrelid
      and a.attnum = d.adnum
    where d.adrelid = 'public.profiles'::regclass
      and a.attname = 'created_at'
  ),
  'now()',
  'profile creation time is generated by PostgreSQL'
);

select ok(
  exists (
    select 1
    from pg_constraint as c
    join pg_attribute as source_column
      on source_column.attrelid = c.conrelid
      and source_column.attnum = c.conkey[1]
    join pg_attribute as target_column
      on target_column.attrelid = c.confrelid
      and target_column.attnum = c.confkey[1]
    where c.conname = 'profiles_id_fkey'
      and c.contype = 'f'
      and c.conrelid = 'public.profiles'::regclass
      and c.confrelid = 'auth.users'::regclass
      and source_column.attname = 'id'
      and target_column.attname = 'id'
      and cardinality(c.conkey) = 1
  ),
  'profile IDs reference the primary Auth user identifier'
);

select is(
  (
    select c.confdeltype::text
    from pg_constraint as c
    where c.conname = 'profiles_id_fkey'
      and c.conrelid = 'public.profiles'::regclass
  ),
  'r',
  'Auth user deletion is explicitly restricted'
);

select is(
  (
    select c.relrowsecurity
    from pg_class as c
    where c.oid = 'public.profiles'::regclass
  ),
  true,
  'row-level security is enabled on profiles'
);

select is(
  (
    select count(*)
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
  ),
  3::bigint,
  'profiles has only the three reviewed operation-specific policies'
);

select ok(
  exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'Authenticated users can read their own profile anchor'
      and cmd = 'SELECT'
      and roles = array['authenticated']::name[]
  ),
  'the read-own policy targets authenticated users explicitly'
);

select ok(
  exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'Authenticated users can create their own profile anchor'
      and cmd = 'INSERT'
      and roles = array['authenticated']::name[]
  ),
  'the create-own policy targets authenticated users explicitly'
);

select ok(
  not exists (
    select 1
    from pg_trigger as t
    join pg_proc as p on p.oid = t.tgfoid
    join pg_namespace as n on n.oid = p.pronamespace
    where t.tgrelid = 'auth.users'::regclass
      and not t.tgisinternal
      and n.nspname in ('public', 'private')
  ),
  'PLANETS installs no automatic profile-creation trigger on Auth users'
);

select is(
  (
    select bool_or(has_table_privilege('anon', 'public.profiles', privilege_name))
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'anon receives no profile table privilege'
);

select is(
  has_table_privilege('authenticated', 'public.profiles', 'SELECT'),
  true,
  'authenticated receives the reviewed profile read grant'
);

select is(
  has_table_privilege('authenticated', 'public.profiles', 'INSERT'),
  false,
  'authenticated does not receive table-wide profile insert permission'
);

select is(
  has_column_privilege('authenticated', 'public.profiles', 'id', 'INSERT'),
  true,
  'authenticated may insert only the profile identifier column'
);

select is(
  has_column_privilege('authenticated', 'public.profiles', 'created_at', 'INSERT'),
  false,
  'authenticated cannot supply the canonical profile creation time'
);

select is(
  has_column_privilege('authenticated', 'public.profiles', 'display_name', 'UPDATE'),
  true,
  'authenticated may update the own display name through the reviewed policy'
);

select is(
  has_column_privilege('authenticated', 'public.profiles', 'updated_at', 'UPDATE'),
  false,
  'authenticated cannot supply the database-maintained update timestamp'
);

select is(
  (
    select bool_or(
      has_table_privilege('authenticated', 'public.profiles', privilege_name)
    )
    from unnest(array['UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'authenticated cannot update or delete profile anchors'
);

select is(
  (
    select bool_or(
      has_table_privilege('service_role', 'public.profiles', privilege_name)
    )
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'service_role receives no convenience profile grant'
);

select * from finish();

rollback;
