begin;

select plan(36);

select has_table('private', 'audit_events', 'the private audit event table exists');

select has_table('private', 'outbox_events', 'the private outbox event table exists');

select columns_are(
  'private',
  'audit_events',
  array['id', 'action', 'actor_user_id', 'target_type', 'target_id', 'metadata', 'created_at'],
  'audit events contain only the minimal operational-history fields'
);

select columns_are(
  'private',
  'outbox_events',
  array['id', 'event_type', 'payload', 'created_at', 'available_at', 'published_at'],
  'outbox events contain only the minimal handoff fields'
);

select col_is_pk('private', 'audit_events', 'id', 'audit event IDs are primary keys');

select col_is_pk('private', 'outbox_events', 'id', 'outbox event IDs are primary keys');

select is(
  (
    select pg_get_expr(d.adbin, d.adrelid)
    from pg_attrdef as d
    join pg_attribute as a
      on a.attrelid = d.adrelid
      and a.attnum = d.adnum
    where d.adrelid = 'private.audit_events'::regclass
      and a.attname = 'id'
  ),
  'gen_random_uuid()',
  'audit event IDs are generated by PostgreSQL'
);

select is(
  (
    select pg_get_expr(d.adbin, d.adrelid)
    from pg_attrdef as d
    join pg_attribute as a
      on a.attrelid = d.adrelid
      and a.attnum = d.adnum
    where d.adrelid = 'private.outbox_events'::regclass
      and a.attname = 'id'
  ),
  'gen_random_uuid()',
  'outbox event IDs are generated by PostgreSQL'
);

insert into auth.users (id, email)
values ('30000000-0000-4000-8000-000000000003', 'audit-actor@planets.invalid');

select lives_ok(
  $$
    insert into private.audit_events (action, actor_user_id, target_type, target_id)
    values (
      'profile.anchor_created',
      '30000000-0000-4000-8000-000000000003',
      'profile',
      '30000000-0000-4000-8000-000000000003'
    )
  $$,
  'a trusted database operation can append a valid audit event'
);

select ok(
  exists (
    select 1
    from private.audit_events
    where action = 'profile.anchor_created'
      and id is not null
      and metadata = '{}'::jsonb
      and jsonb_typeof(metadata) = 'object'
      and created_at is not null
      and created_at <= now()
  ),
  'audit event identifiers, metadata, and timestamps have canonical defaults'
);

select throws_ok(
  $$insert into private.audit_events (action) values ('')$$,
  '23514',
  'new row for relation "audit_events" violates check constraint "audit_events_action_nonempty"',
  'an empty audit action is rejected'
);

select throws_ok(
  $$insert into private.audit_events (action) values ('   ')$$,
  '23514',
  'new row for relation "audit_events" violates check constraint "audit_events_action_nonempty"',
  'a whitespace-only audit action is rejected'
);

select throws_ok(
  $$insert into private.audit_events (action, target_type) values ('test.action', '   ')$$,
  '23514',
  'new row for relation "audit_events" violates check constraint "audit_events_target_type_nonempty"',
  'a supplied audit target type must be meaningful'
);

select throws_ok(
  $$insert into private.audit_events (action, metadata) values ('test.action', '[]'::jsonb)$$,
  '23514',
  'new row for relation "audit_events" violates check constraint "audit_events_metadata_object"',
  'audit metadata must be a JSON object'
);

select ok(
  exists (
    select 1
    from pg_constraint as c
    where c.conname = 'audit_events_actor_user_id_fkey'
      and c.contype = 'f'
      and c.conrelid = 'private.audit_events'::regclass
      and c.confrelid = 'auth.users'::regclass
  ),
  'audit actors reference Supabase Auth identities'
);

select is(
  (
    select c.confdeltype::text
    from pg_constraint as c
    where c.conname = 'audit_events_actor_user_id_fkey'
      and c.conrelid = 'private.audit_events'::regclass
  ),
  'r',
  'audit actor deletion is explicitly restricted'
);

select throws_ok(
  $$delete from auth.users where id = '30000000-0000-4000-8000-000000000003'$$,
  '23503',
  'update or delete on table "users" violates foreign key constraint "audit_events_actor_user_id_fkey" on table "audit_events"',
  'raw Auth deletion cannot silently rewrite actor-linked audit history'
);

select is(
  (
    select count(*)
    from private.audit_events
    where actor_user_id = '30000000-0000-4000-8000-000000000003'
  ),
  1::bigint,
  'the failed Auth deletion leaves the audit event intact'
);

select ok(
  to_regclass('private.audit_events_created_at_idx') is not null,
  'audit events have a chronological lookup index'
);

select ok(
  to_regclass('private.audit_events_actor_user_id_created_at_idx') is not null,
  'audit events have an actor chronology lookup index'
);

select lives_ok(
  $$insert into private.outbox_events (event_type) values ('profile.anchor_created')$$,
  'a trusted database operation can append a valid outbox event'
);

select ok(
  exists (
    select 1
    from private.outbox_events
    where event_type = 'profile.anchor_created'
      and id is not null
      and payload = '{}'::jsonb
      and jsonb_typeof(payload) = 'object'
      and created_at is not null
      and available_at >= created_at
      and published_at is null
  ),
  'outbox identifiers, payloads, availability, and completion state have canonical defaults'
);

select throws_ok(
  $$insert into private.outbox_events (event_type) values ('')$$,
  '23514',
  'new row for relation "outbox_events" violates check constraint "outbox_events_event_type_nonempty"',
  'an empty outbox event type is rejected'
);

select throws_ok(
  $$insert into private.outbox_events (event_type) values ('   ')$$,
  '23514',
  'new row for relation "outbox_events" violates check constraint "outbox_events_event_type_nonempty"',
  'a whitespace-only outbox event type is rejected'
);

select throws_ok(
  $$
    insert into private.outbox_events (event_type, payload)
    values ('test.event', '[]'::jsonb)
  $$,
  '23514',
  'new row for relation "outbox_events" violates check constraint "outbox_events_payload_object"',
  'outbox payloads must be JSON objects'
);

select throws_ok(
  $$
    insert into private.outbox_events (event_type, created_at, available_at)
    values ('test.event', '2026-01-02 00:00:00+00', '2026-01-01 00:00:00+00')
  $$,
  '23514',
  'new row for relation "outbox_events" violates check constraint "outbox_events_available_at_not_before_created_at"',
  'outbox availability cannot precede event creation'
);

select throws_ok(
  $$
    insert into private.outbox_events (event_type, created_at, published_at)
    values ('test.event', '2026-01-02 00:00:00+00', '2026-01-01 00:00:00+00')
  $$,
  '23514',
  'new row for relation "outbox_events" violates check constraint "outbox_events_published_at_not_before_created_at"',
  'outbox publication cannot precede event creation'
);

select ok(
  (
    select i.indisvalid
      and pg_get_indexdef(i.indexrelid) like '%(available_at, created_at, id)%'
    from pg_index as i
    where i.indexrelid = 'private.outbox_events_pending_available_at_idx'::regclass
  ),
  'the pending-outbox index supports availability and creation ordering'
);

select is(
  (
    select lower(pg_get_expr(i.indpred, i.indrelid))
    from pg_index as i
    where i.indexrelid = 'private.outbox_events_pending_available_at_idx'::regclass
  ),
  '(published_at is null)',
  'the pending-outbox index contains only unpublished events'
);

select is(
  (
    select bool_or(
      has_table_privilege('anon', 'private.audit_events', privilege_name)
    )
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'anon receives no direct audit-event privilege'
);

select is(
  (
    select bool_or(
      has_table_privilege('authenticated', 'private.audit_events', privilege_name)
    )
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'authenticated receives no direct audit-event privilege'
);

select is(
  (
    select bool_or(
      has_table_privilege('service_role', 'private.audit_events', privilege_name)
    )
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'service_role receives no direct audit-event privilege'
);

select is(
  (
    select bool_or(
      has_table_privilege('anon', 'private.outbox_events', privilege_name)
    )
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'anon receives no direct outbox-event privilege'
);

select is(
  (
    select bool_or(
      has_table_privilege('authenticated', 'private.outbox_events', privilege_name)
    )
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'authenticated receives no direct outbox-event privilege'
);

select is(
  (
    select bool_or(
      has_table_privilege('service_role', 'private.outbox_events', privilege_name)
    )
    from unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE']) as privileges(privilege_name)
  ),
  false,
  'service_role receives no direct outbox-event privilege'
);

select is(
  (
    select bool_or(c.relrowsecurity)
    from pg_class as c
    where c.oid in (
      'private.audit_events'::regclass,
      'private.outbox_events'::regclass
    )
  ),
  false,
  'private schema isolation is the boundary; private primitives do not use ceremonial RLS'
);

select * from finish();

rollback;
