begin;

select no_plan();

select has_table(
  'public',
  'resource_request_chats',
  'the accepted resource-request chat anchor exists'
);
select columns_are(
  'public',
  'resource_request_chats',
  array['id', 'request_id', 'activated_at'],
  'resource chat anchors contain only request identity and activation time'
);
select col_type_is(
  'public',
  'resource_request_chats',
  'id',
  'uuid',
  'resource chat IDs are UUIDs'
);
select col_is_pk(
  'public',
  'resource_request_chats',
  'id',
  'resource chat identity is the primary key'
);
select col_not_null(
  'public',
  'resource_request_chats',
  'request_id',
  'every resource chat belongs to one request episode'
);
select col_not_null(
  'public',
  'resource_request_chats',
  'activated_at',
  'resource chat activation is always recorded'
);
select is(
  (
    select count(*)
    from pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.resource_request_chats'::regclass
      and constraint_row.contype = 'u'
      and pg_get_constraintdef(constraint_row.oid) = 'UNIQUE (request_id)'
  ),
  1::bigint,
  'one request episode owns at most one resource chat'
);
select is(
  (
    select count(*)
    from pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.resource_request_chats'::regclass
      and constraint_row.contype = 'f'
      and constraint_row.confrelid =
        'public.resource_listing_requests'::regclass
      and constraint_row.confdeltype = 'r'
  ),
  1::bigint,
  'chat anchors retain their canonical request with restrictive deletion'
);
select ok(
  to_regprocedure('private.validate_resource_request_chat_anchor()')
    is not null
    and exists (
      select 1
      from pg_trigger as trigger_row
      where trigger_row.tgrelid = 'public.resource_request_chats'::regclass
        and trigger_row.tgname = 'resource_request_chats_validate_anchor'
        and not trigger_row.tgisinternal
    ),
  'a trigger prevents chat anchors for non-accepted requests'
);

select has_table(
  'public',
  'resource_request_chat_messages',
  'the durable human resource-chat message table exists'
);
select columns_are(
  'public',
  'resource_request_chat_messages',
  array['id', 'chat_id', 'sender_profile_id', 'body', 'created_at'],
  'resource messages contain only canonical human-message fields'
);
select results_eq(
  $$
    select
      column_name::text collate "C",
      data_type::text collate "C",
      is_nullable::text collate "C"
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'resource_request_chat_messages'
    order by ordinal_position
  $$,
  $$values
    ('id'::text collate "C", 'uuid'::text collate "C", 'NO'::text collate "C"),
    ('chat_id'::text collate "C", 'uuid'::text collate "C", 'NO'::text collate "C"),
    ('sender_profile_id'::text collate "C", 'uuid'::text collate "C", 'NO'::text collate "C"),
    ('body'::text collate "C", 'text'::text collate "C", 'NO'::text collate "C"),
    ('created_at'::text collate "C", 'timestamp with time zone'::text collate "C", 'NO'::text collate "C")
  $$,
  'resource message types and nullability are canonical'
);
select ok(
  (
    select column_default like '%gen_random_uuid()%'
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'resource_request_chat_messages'
      and column_name = 'id'
  ),
  'message IDs are generated by the database'
);
select ok(
  (
    select column_default like '%statement_timestamp()%'
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'resource_request_chat_messages'
      and column_name = 'created_at'
  ),
  'message timestamps have a server-owned default'
);
select ok(
  (
    select pg_get_constraintdef(constraint_row.oid)
    from pg_constraint as constraint_row
    where constraint_row.conrelid =
      'public.resource_request_chat_messages'::regclass
      and constraint_row.conname =
        'resource_request_chat_messages_body_canonical'
  ) ilike '%regexp_replace%'
    and (
      select pg_get_constraintdef(constraint_row.oid)
      from pg_constraint as constraint_row
      where constraint_row.conrelid =
        'public.resource_request_chat_messages'::regclass
        and constraint_row.conname =
          'resource_request_chat_messages_body_canonical'
    ) ilike '%char_length(body)%1%4000%',
  'message bodies are trimmed and bounded to 4,000 Unicode characters'
);
select is(
  (
    select count(*)
    from pg_constraint as constraint_row
    where constraint_row.conrelid =
      'public.resource_request_chat_messages'::regclass
      and constraint_row.contype = 'f'
      and constraint_row.confrelid =
        'public.resource_request_chats'::regclass
      and constraint_row.confdeltype = 'r'
  ),
  1::bigint,
  'messages retain their chat anchor'
);
select is(
  (
    select count(*)
    from pg_constraint as constraint_row
    where constraint_row.conrelid =
      'public.resource_request_chat_messages'::regclass
      and constraint_row.contype = 'f'
      and constraint_row.confrelid = 'public.profiles'::regclass
      and constraint_row.confdeltype = 'r'
  ),
  1::bigint,
  'messages retain their sender identity'
);
select ok(
  to_regprocedure(
    'private.protect_resource_request_chat_message_immutability()'
  ) is not null
    and exists (
      select 1
      from pg_trigger as trigger_row
      where trigger_row.tgrelid =
        'public.resource_request_chat_messages'::regclass
        and trigger_row.tgname =
          'resource_request_chat_messages_immutable'
        and not trigger_row.tgisinternal
    ),
  'a database trigger protects messages from update and deletion'
);

select results_eq(
  $$
    select indexname::text collate "C"
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'resource_request_chat_messages'
      and indexname <> 'resource_request_chat_messages_pkey'
    order by indexname collate "C"
  $$,
  $$values
    ('resource_request_chat_messages_chat_created_idx'::text collate "C"),
    ('resource_request_chat_messages_sender_created_idx'::text collate "C")
  $$,
  'message indexes cover keyset history and both foreign-key paths'
);
select ok(
  (
    select indexdef
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'resource_request_chat_messages'
      and indexname = 'resource_request_chat_messages_chat_created_idx'
  ) ilike '%(chat_id, created_at desc, id desc)%',
  'the history index exactly matches descending keyset pagination'
);

select is(
  (
    select bool_and(class.relrowsecurity)
    from pg_class as class
    where class.oid in (
      'public.resource_request_chats'::regclass,
      'public.resource_request_chat_messages'::regclass
    )
  ),
  true,
  'RLS is enabled on both exposed-schema resource-chat tables'
);
select is(
  (
    select count(*)
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'resource_request_chats',
        'resource_request_chat_messages'
      )
  ),
  0::bigint,
  'resource chats have no direct client policies because access is RPC-only'
);
select is(
  (
    select bool_and(
      not has_table_privilege(role_name, table_name, privilege_name)
    )
    from unnest(array['anon', 'authenticated', 'service_role'])
      as role_name
    cross join unnest(array[
      'public.resource_request_chats',
      'public.resource_request_chat_messages'
    ]) as table_name
    cross join unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE'])
      as privilege_name
  ),
  true,
  'client and broad service roles have no direct resource-chat table access'
);

select ok(
  to_regprocedure(
    'private.ensure_resource_request_chat_for_request(uuid,timestamptz)'
  ) is not null
    and to_regprocedure(
      'private.resource_request_chat_realtime_topic(uuid,uuid)'
    ) is not null
    and to_regprocedure(
      'private.profile_can_receive_resource_request_chat_topic(text)'
    ) is not null,
  'chat activation and strict private-topic helpers exist'
);
select ok(
  to_regprocedure(
    'public.send_resource_request_chat_message(uuid,uuid,text)'
  ) is not null,
  'the expected-identity send RPC exists'
);
select ok(
  to_regprocedure(
    'public.list_own_resource_request_chat_messages(uuid,uuid,integer,timestamptz,uuid)'
  ) is not null,
  'the keyset resource-chat history RPC exists'
);
select ok(
  to_regprocedure(
    'public.get_own_resource_request_chat(uuid,uuid)'
  ) is not null,
  'the exact resource-chat summary RPC exists'
);
select ok(
  to_regprocedure(
    'public.list_own_resource_request_chats(uuid,integer,timestamptz,uuid)'
  ) is not null,
  'the resource-chat list RPC exists'
);

select is(
  pg_get_function_result(
    'public.send_resource_request_chat_message(uuid,uuid,text)'::regprocedure
  ),
  'TABLE(message_id uuid, chat_id uuid, sender_profile_id uuid, created_at timestamp with time zone, body text)',
  'send returns the canonical durable message contract'
);
select is(
  pg_get_function_result(
    'public.list_own_resource_request_chat_messages(uuid,uuid,integer,timestamptz,uuid)'::regprocedure
  ),
  'TABLE(message_id uuid, chat_id uuid, sender_profile_id uuid, sender_display_name text, body text, created_at timestamp with time zone)',
  'history returns only human-message and sender display fields'
);
select is(
  pg_get_function_result(
    'public.get_own_resource_request_chat(uuid,uuid)'::regprocedure
  ),
  'TABLE(chat_id uuid, request_id uuid, agreement_id uuid, listing_id uuid, listing_title text, viewer_role text, owner_profile_id uuid, owner_display_name text, requester_profile_id uuid, requester_display_name text, agreement_lifecycle text, coordination_closed_at timestamp with time zone, has_send_entitlement boolean, activated_at timestamp with time zone, last_visible_message_id uuid, last_visible_message_body text, last_visible_message_at timestamp with time zone, last_visible_sender_profile_id uuid, last_visible_sender_display_name text, activity_at timestamp with time zone)',
  'the exact summary has the resource-specific counterparty and activity shape'
);
select is(
  pg_get_function_result(
    'public.list_own_resource_request_chats(uuid,integer,timestamptz,uuid)'::regprocedure
  ),
  pg_get_function_result(
    'public.get_own_resource_request_chat(uuid,uuid)'::regprocedure
  ),
  'the exact and list APIs share one summary shape'
);

select is(
  (
    select bool_and(
      has_function_privilege('authenticated', procedure_oid, 'EXECUTE')
      and not has_function_privilege('anon', procedure_oid, 'EXECUTE')
      and not has_function_privilege(
        'service_role',
        procedure_oid,
        'EXECUTE'
      )
    )
    from unnest(array[
      'public.send_resource_request_chat_message(uuid,uuid,text)'::regprocedure,
      'public.list_own_resource_request_chat_messages(uuid,uuid,integer,timestamptz,uuid)'::regprocedure,
      'public.get_own_resource_request_chat(uuid,uuid)'::regprocedure,
      'public.list_own_resource_request_chats(uuid,integer,timestamptz,uuid)'::regprocedure
    ]) as procedure_oid
  ),
  true,
  'only authenticated clients execute resource-chat APIs'
);
select is(
  (
    select bool_and(
      not has_function_privilege(role_name, procedure_oid, 'EXECUTE')
    )
    from unnest(array['anon', 'authenticated', 'service_role'])
      as role_name
    cross join unnest(array[
      'private.validate_resource_request_chat_anchor()'::regprocedure,
      'private.ensure_resource_request_chat_for_request(uuid,timestamptz)'::regprocedure,
      'private.protect_resource_request_chat_message_immutability()'::regprocedure,
      'private.resource_request_chat_realtime_topic(uuid,uuid)'::regprocedure
    ]) as procedure_oid
  ),
  true,
  'private resource-chat helpers are not directly client executable'
);
select ok(
  has_function_privilege(
    'authenticated',
    'private.profile_can_receive_resource_request_chat_topic(text)',
    'EXECUTE'
  )
    and not has_function_privilege(
      'anon',
      'private.profile_can_receive_resource_request_chat_topic(text)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'service_role',
      'private.profile_can_receive_resource_request_chat_topic(text)',
      'EXECUTE'
    ),
  'only authenticated Realtime policy evaluation can execute the topic predicate'
);

select results_eq(
  $$
    select
      policyname::text collate "C",
      cmd::text collate "C",
      roles::text collate "C"
    from pg_policies
    where schemaname = 'realtime'
      and tablename = 'messages'
      and policyname =
        'resource_request_chat_counterparties_receive_broadcasts'
  $$,
  $$values (
    'resource_request_chat_counterparties_receive_broadcasts'::text collate "C",
    'SELECT'::text collate "C",
    '{authenticated}'::text collate "C"
  )$$,
  'resource-chat Realtime authorization is receive-only and authenticated'
);
select is(
  (
    select qual ilike '%profile_can_receive_resource_request_chat_topic%'
      and qual ilike '%realtime.topic%'
      and qual ilike '%extension%broadcast%'
    from pg_policies
    where schemaname = 'realtime'
      and tablename = 'messages'
      and policyname =
        'resource_request_chat_counterparties_receive_broadcasts'
  ),
  true,
  'the policy binds Broadcast reads to the strict resource-chat topic helper'
);
select is(
  (
    select count(*)
    from pg_policies
    where schemaname = 'realtime'
      and tablename = 'messages'
      and policyname like 'resource_request_chat%'
      and cmd in ('INSERT', 'UPDATE', 'DELETE', 'ALL')
  ),
  0::bigint,
  'resource-chat clients receive hints but cannot publish generic Broadcasts'
);

select ok(
  pg_get_functiondef(
    'private.accept_resource_listing_request_without_block(uuid,uuid)'::regprocedure
  ) ilike '%ensure_resource_request_chat_for_request%'
    and pg_get_functiondef(
      'private.accept_resource_listing_request_without_block(uuid,uuid)'::regprocedure
    ) ilike '%ensure_resource_exchange_agreement_for_request%'
    and pg_get_functiondef(
      'public.accept_resource_listing_request(uuid,uuid)'::regprocedure
    ) ilike '%accept_resource_listing_request_without_block%',
  'the preserved acceptance core atomically ensures both coordination anchors and the public barrier delegates to it'
);
select ok(
  pg_get_functiondef(
    'public.send_resource_request_chat_message(uuid,uuid,text)'::regprocedure
  ) ilike '%for update%resource_exchange_agreements%'
    or pg_get_functiondef(
      'public.send_resource_request_chat_message(uuid,uuid,text)'::regprocedure
    ) ilike '%resource_exchange_agreements%for update%',
  'send serializes on the canonical agreement row'
);
select ok(
  pg_get_functiondef(
    'private.record_resource_exchange_agreement_event(text,uuid,uuid,text,uuid,timestamptz)'::regprocedure
  ) ilike '%resource.exchange_changed%'
    and pg_get_functiondef(
      'private.record_resource_exchange_agreement_event(text,uuid,uuid,text,uuid,timestamptz)'::regprocedure
    ) ilike '%realtime.send%',
  'agreement transitions emit a private identifier-only resource refresh hint'
);
select is(
  (
    select count(*)
    from unnest(array[
      pg_get_functiondef(
        'public.send_resource_request_chat_message(uuid,uuid,text)'::regprocedure
      ),
      pg_get_functiondef(
        'private.record_resource_exchange_agreement_event(text,uuid,uuid,text,uuid,timestamptz)'::regprocedure
      )
    ]) as definition
    where definition ~ '40001'
  ),
  0::bigint,
  'resource-chat functions do not misuse PostgreSQL serialization SQLSTATE'
);
select is(
  (
    select count(*)
    from pg_publication_tables
    where schemaname = 'public'
      and tablename in (
        'resource_request_chats',
        'resource_request_chat_messages'
      )
  ),
  0::bigint,
  'resource-chat rows are not exposed through broad Postgres Changes'
);

select * from finish();

rollback;
