begin;

select no_plan();

select has_table(
  'public',
  'project_join_request_chats',
  'participation-request chat anchors exist'
);
select columns_are(
  'public',
  'project_join_request_chats',
  array['id', 'request_id', 'activated_at'],
  'chat anchors contain only episode identity and activation time'
);
select col_is_pk(
  'public',
  'project_join_request_chats',
  'id',
  'chat identity is the primary key'
);
select is(
  (
    select count(*)
    from pg_constraint as constraint_row
    where constraint_row.conrelid =
      'public.project_join_request_chats'::regclass
      and constraint_row.contype = 'u'
      and pg_get_constraintdef(constraint_row.oid) = 'UNIQUE (request_id)'
  ),
  1::bigint,
  'one request episode owns exactly one chat anchor'
);
select is(
  (
    select count(*)
    from pg_constraint as constraint_row
    where constraint_row.conrelid =
      'public.project_join_request_chats'::regclass
      and constraint_row.contype = 'f'
      and constraint_row.confrelid = 'public.project_join_requests'::regclass
      and constraint_row.confdeltype = 'r'
  ),
  1::bigint,
  'chat anchors retain their canonical request with restrictive deletion'
);
select ok(
  exists (
    select 1
    from pg_trigger as trigger_row
    where trigger_row.tgrelid = 'public.project_join_requests'::regclass
      and trigger_row.tgname = 'project_join_requests_create_private_chat'
      and not trigger_row.tgisinternal
  ),
  'every new request atomically creates its private chat'
);

select has_table(
  'public',
  'project_join_request_chat_messages',
  'durable human request-chat messages exist'
);
select columns_are(
  'public',
  'project_join_request_chat_messages',
  array['id', 'chat_id', 'sender_profile_id', 'body', 'created_at'],
  'messages contain only canonical human-message fields'
);
select ok(
  (
    select column_default like '%gen_random_uuid()%'
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'project_join_request_chat_messages'
      and column_name = 'id'
  ),
  'message IDs are generated by the database'
);
select ok(
  (
    select column_default like '%statement_timestamp()%'
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'project_join_request_chat_messages'
      and column_name = 'created_at'
  ),
  'message timestamps have a server-owned default'
);
select ok(
  (
    select pg_get_constraintdef(constraint_row.oid)
    from pg_constraint as constraint_row
    where constraint_row.conrelid =
      'public.project_join_request_chat_messages'::regclass
      and constraint_row.conname =
        'project_join_request_chat_messages_body_canonical'
  ) ilike '%regexp_replace%'
    and (
      select pg_get_constraintdef(constraint_row.oid)
      from pg_constraint as constraint_row
      where constraint_row.conrelid =
        'public.project_join_request_chat_messages'::regclass
        and constraint_row.conname =
          'project_join_request_chat_messages_body_canonical'
    ) ilike '%char_length(body)%1%4000%',
  'message bodies are canonical and bounded to 4,000 characters'
);
select is(
  (
    select count(*)
    from pg_constraint as constraint_row
    where constraint_row.conrelid =
      'public.project_join_request_chat_messages'::regclass
      and constraint_row.contype = 'f'
      and constraint_row.confdeltype = 'r'
  ),
  2::bigint,
  'message chat and sender foreign keys both restrict deletion'
);
select results_eq(
  $$
    select indexname::text collate "C"
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'project_join_request_chat_messages'
      and indexname <> 'project_join_request_chat_messages_pkey'
    order by indexname collate "C"
  $$,
  $$values
    ('project_join_request_chat_messages_chat_created_idx'::text collate "C"),
    ('project_join_request_chat_messages_sender_created_idx'::text collate "C")
  $$,
  'message indexes cover pagination and both foreign-key paths'
);
select ok(
  exists (
    select 1
    from pg_trigger as trigger_row
    where trigger_row.tgrelid =
      'public.project_join_request_chat_messages'::regclass
      and trigger_row.tgname =
        'project_join_request_chat_messages_immutable'
      and not trigger_row.tgisinternal
  ),
  'human messages are protected from update and deletion'
);

select is(
  (
    select bool_and(class.relrowsecurity)
    from pg_class as class
    where class.oid in (
      'public.project_join_request_chats'::regclass,
      'public.project_join_request_chat_messages'::regclass
    )
  ),
  true,
  'RLS is enabled on both exposed-schema tables'
);
select is(
  (
    select count(*)
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'project_join_request_chats',
        'project_join_request_chat_messages'
      )
  ),
  0::bigint,
  'request chats expose no direct client policies'
);
select is(
  (
    select bool_and(
      not has_table_privilege(role_name, table_name, privilege_name)
    )
    from unnest(array['anon', 'authenticated', 'service_role'])
      as role_name
    cross join unnest(array[
      'public.project_join_request_chats',
      'public.project_join_request_chat_messages'
    ]) as table_name
    cross join unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE'])
      as privilege_name
  ),
  true,
  'clients and the broad service role have no direct table privileges'
);

select ok(
  to_regprocedure(
    'public.send_project_join_request_chat_message(uuid,uuid,text)'
  ) is not null
    and to_regprocedure(
      'public.get_own_project_join_request_chat(uuid,uuid)'
    ) is not null
    and to_regprocedure(
      'public.list_own_project_join_request_chat_items(uuid,uuid,integer,timestamptz,text,uuid)'
    ) is not null,
  'the expected-identity send, exact-read, and keyset-feed APIs exist'
);
select is(
  pg_get_function_result(
    'public.send_project_join_request_chat_message(uuid,uuid,text)'::regprocedure
  ),
  'TABLE(message_id uuid, chat_id uuid, sender_profile_id uuid, created_at timestamp with time zone, body text)',
  'send returns the canonical durable human-message contract'
);
select is(
  pg_get_function_result(
    'public.get_own_project_join_request_chat(uuid,uuid)'::regprocedure
  ),
  'TABLE(chat_id uuid, request_id uuid, project_id uuid, project_kind text, project_title text, viewer_role text, requester_profile_id uuid, requester_display_name text, creator_profile_id uuid, creator_display_name text, request_status text, request_message text, request_created_at timestamp with time zone, resolved_at timestamp with time zone, activated_at timestamp with time zone, is_read_only boolean, has_send_entitlement boolean, accepted_project_group_chat_id uuid)',
  'the exact read exposes identity, participants, state, entitlement, and accepted group-chat continuation'
);
select is(
  pg_get_function_result(
    'public.list_own_project_join_request_chat_items(uuid,uuid,integer,timestamptz,text,uuid)'::regprocedure
  ),
  'TABLE(item_kind text, item_id uuid, chat_id uuid, request_id uuid, message_id uuid, project_id uuid, project_kind text, project_title text, request_status text, request_message text, requester_profile_id uuid, requester_display_name text, sender_profile_id uuid, sender_display_name text, body text, created_at timestamp with time zone)',
  'the feed exposes a strict structured-request or human-message union'
);
select is(
  (
    select bool_and(
      has_function_privilege('authenticated', procedure_oid, 'EXECUTE')
      and not has_function_privilege('anon', procedure_oid, 'EXECUTE')
      and not has_function_privilege('service_role', procedure_oid, 'EXECUTE')
    )
    from unnest(array[
      'public.send_project_join_request_chat_message(uuid,uuid,text)'::regprocedure,
      'public.get_own_project_join_request_chat(uuid,uuid)'::regprocedure,
      'public.list_own_project_join_request_chat_items(uuid,uuid,integer,timestamptz,text,uuid)'::regprocedure
    ]) as procedure_oid
  ),
  true,
  'only authenticated clients execute request-chat APIs'
);
select is(
  (
    select bool_and(
      not has_function_privilege(role_name, procedure_oid, 'EXECUTE')
    )
    from unnest(array['anon', 'authenticated', 'service_role'])
      as role_name
    cross join unnest(array[
      'private.validate_project_join_request_chat_anchor()'::regprocedure,
      'private.create_project_join_request_chat()'::regprocedure,
      'private.protect_project_join_request_chat_message_immutability()'::regprocedure,
      'private.project_join_request_chat_realtime_topic(uuid,uuid)'::regprocedure
    ]) as procedure_oid
  ),
  true,
  'private mutation and topic helpers are not directly executable'
);
select ok(
  has_function_privilege(
    'authenticated',
    'private.profile_can_receive_project_join_request_chat_topic(text)',
    'EXECUTE'
  )
    and not has_function_privilege(
      'anon',
      'private.profile_can_receive_project_join_request_chat_topic(text)',
      'EXECUTE'
    ),
  'only authenticated Realtime policy evaluation executes the topic predicate'
);

select results_eq(
  $$
    select
      policyname::text collate "C",
      cmd::text collate "C",
      roles::text collate "C"
    from pg_policies
    where schemaname = 'realtime'
      and tablename = 'messages'
      and policyname =
        'project_join_request_chat_counterparties_receive_broadcasts'
  $$,
  $$values (
    'project_join_request_chat_counterparties_receive_broadcasts'::text collate "C",
    'SELECT'::text collate "C",
    '{authenticated}'::text collate "C"
  )$$,
  'Realtime authorization is receive-only and authenticated'
);
select is(
  (
    select qual ilike '%profile_can_receive_project_join_request_chat_topic%'
      and qual ilike '%realtime.topic%'
      and qual ilike '%extension%broadcast%'
    from pg_policies
    where schemaname = 'realtime'
      and tablename = 'messages'
      and policyname =
        'project_join_request_chat_counterparties_receive_broadcasts'
  ),
  true,
  'the Realtime policy binds Broadcast reads to the strict topic predicate'
);
select is(
  (
    select count(*)
    from pg_publication_tables
    where schemaname = 'public'
      and tablename in (
        'project_join_request_chats',
        'project_join_request_chat_messages'
      )
  ),
  0::bigint,
  'request-chat rows are not exposed through broad Postgres Changes'
);

select ok(
  pg_get_functiondef(
    'public.send_project_join_request_chat_message(uuid,uuid,text)'::regprocedure
  ) ilike '%lock_project_for_participation%'
    and pg_get_functiondef(
      'public.send_project_join_request_chat_message(uuid,uuid,text)'::regprocedure
    ) ilike '%for update of request%'
    and pg_get_functiondef(
      'public.send_project_join_request_chat_message(uuid,uuid,text)'::regprocedure
    ) ilike '%PT409%',
  'send serializes with request transitions and rejects resolved conversations'
);
select ok(
  pg_get_functiondef(
    'public.send_project_join_request_chat_message(uuid,uuid,text)'::regprocedure
  ) ilike '%project.join_request_chat_message_sent%'
    and pg_get_functiondef(
      'public.send_project_join_request_chat_message(uuid,uuid,text)'::regprocedure
    ) ilike '%realtime.send%',
  'send emits the identifier-only durable event and private Realtime hint'
);
select ok(
  pg_get_functiondef(
    'public.process_notification_outbox_batch(integer)'::regprocedure
  ) not ilike '%project.join_request_chat_message_sent%'
    and pg_get_functiondef(
      'public.process_push_outbox_batch(integer)'::regprocedure
    ) not ilike '%project.join_request_chat_message_sent%',
  'existing notification and push consumers safely leave request-chat events for 07C1B'
);
select is(
  (
    select count(*)
    from public.project_join_requests as request
    left join public.project_join_request_chats as chat
      on chat.request_id = request.id
      and chat.activated_at = request.created_at
    where chat.id is null
  ),
  0::bigint,
  'migration backfill leaves every historical request with one canonical chat'
);

select * from finish();

rollback;
