begin;
select no_plan();
create function pg_temp.person(n integer) returns uuid language sql immutable as $$
  select format('fb100000-0000-4000-8000-%s',lpad(n::text,12,'0'))::uuid
$$;
insert into auth.users(id,email) select pg_temp.person(n), 'consequence-integration-' || n || '@planets.invalid' from generate_series(1,12) n;
insert into public.profiles(id,display_name) select pg_temp.person(n), 'Consequence person ' || n from generate_series(1,12) n;
insert into public.profile_photos(profile_id,object_path,audience) select pg_temp.person(n), pg_temp.person(n)::text || '/fb900000-0000-4000-8000-000000000001.webp','interactions' from generate_series(1,12) n;
insert into private.moderation_staff_roles(profile_id,staff_role) values(pg_temp.person(1),'moderator');
insert into public.proposals(id,creator_profile_id,lifecycle_state,title,summary,description,starts_at,ends_at,event_timezone,country_code,locality,public_location_label,published_at)
values('fb200000-0000-4000-8000-000000000001',pg_temp.person(2),'published','Consequence visible Project','Synthetic verification','Synthetic verification',statement_timestamp()+interval '2 days',statement_timestamp()+interval '3 days','Europe/Rome','IT','Trento','Trento',statement_timestamp());
insert into public.proposal_meeting_details(proposal_id,exact_meeting_text,exact_location_visibility)
values('fb200000-0000-4000-8000-000000000001','Synthetic private meeting','participants');
update public.projects set registration_capacity=20 where id='fb200000-0000-4000-8000-000000000001';
insert into public.project_delegate_invitations(id,project_id,owner_profile_id,token_digest,status,created_at,expires_at,accepted_at,accepted_by_profile_id,issuer_profile_id,requested_authority_role)
select pg_temp.person(20+n),'fb200000-0000-4000-8000-000000000001',pg_temp.person(2),extensions.digest(n::text,'sha256'),'accepted',statement_timestamp(),statement_timestamp()+interval '7 days',statement_timestamp(),pg_temp.person(n),pg_temp.person(2),case n when 3 then 'co_creator' else 'co_organizer' end from generate_series(3,4) n;
insert into public.project_delegates(project_id,owner_profile_id,delegate_profile_id,invitation_id,delegated_at,granted_by_profile_id,initial_authority_role,authority_role)
select 'fb200000-0000-4000-8000-000000000001',pg_temp.person(2),pg_temp.person(n),pg_temp.person(20+n),(select accepted_at from public.project_delegate_invitations where id=pg_temp.person(20+n)),pg_temp.person(2),case n when 3 then 'co_creator' else 'co_organizer' end,case n when 3 then 'co_creator' else 'co_organizer' end from generate_series(3,4) n;
insert into public.resource_listings(id,owner_profile_id,listing_mode,lifecycle_state,title,description,country_code,locality,public_location_label,published_at)
values('fb300000-0000-4000-8000-000000000001',pg_temp.person(2),'exchange','published','Consequence visible Resource','Synthetic verification','IT','Trento','Trento',statement_timestamp());
insert into public.project_resource_needs(id,project_id,title,details)
values('fb400000-0000-4000-8000-000000000001','fb200000-0000-4000-8000-000000000001','Synthetic resource need','Synthetic coordination');
insert into public.project_covers(project_id,object_path) values('fb200000-0000-4000-8000-000000000001',pg_temp.person(2)::text || '/projects/fb200000-0000-4000-8000-000000000001/fb900000-0000-4000-8000-000000000002.webp');
insert into public.resource_listing_covers(listing_id,object_path) values('fb300000-0000-4000-8000-000000000001',pg_temp.person(2)::text || '/resources/fb300000-0000-4000-8000-000000000001/fb900000-0000-4000-8000-000000000003.webp');
create function pg_temp.case_for(kind text, subject uuid, target uuid) returns uuid language plpgsql as $$
declare result uuid;
begin
  insert into private.moderation_cases(state,subject_profile_id,target_kind,target_profile_id,target_project_id,project_context_id,target_resource_listing_id,resource_listing_context_id)
  values('under_review',subject,kind,case when kind='profile' then target end,case when kind='project' then target end,case when kind='project' then target end,case when kind='resource_listing' then target end,case when kind='resource_listing' then target end) returning id into result;
  return result;
end;
$$;
create function pg_temp.apply(kind text, subject uuid, target uuid, consequence text) returns uuid language plpgsql as $$
declare result uuid;
begin
  perform set_config('request.jwt.claim.sub', pg_temp.person(1)::text,true);
  result:=public.apply_moderation_consequence(pg_temp.person(1),pg_temp.case_for(kind,subject,target),consequence,'Affected reason','Staff-only note');
  return result;
end;
$$;
select set_config('request.jwt.claim.sub',pg_temp.person(5)::text,true);
select set_config('test.mod.project_request',public.request_to_join_project(pg_temp.person(5),'fb200000-0000-4000-8000-000000000001')::text,true);
select set_config('test.mod.resource_request',public.request_resource_listing(pg_temp.person(5),'fb300000-0000-4000-8000-000000000001')::text,true);
select set_config('request.jwt.claim.sub',pg_temp.person(6)::text,true);
select set_config('test.mod.accepted_project_request',public.request_to_join_project(pg_temp.person(6),'fb200000-0000-4000-8000-000000000001')::text,true);
select set_config('test.mod.accepted_resource_request',public.request_resource_listing(pg_temp.person(6),'fb300000-0000-4000-8000-000000000001')::text,true);
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
select public.accept_project_join_request(pg_temp.person(2),current_setting('test.mod.accepted_project_request')::uuid);
select public.accept_resource_listing_request(pg_temp.person(2),current_setting('test.mod.accepted_resource_request')::uuid);
select public.set_project_shared_workspace(pg_temp.person(2),'fb200000-0000-4000-8000-000000000001','https://example.invalid/shared');
select set_config('test.mod.restriction',pg_temp.apply('profile',pg_temp.person(5),pg_temp.person(5),'interaction_restriction')::text,true);
select is((select status from public.project_join_requests where id=current_setting('test.mod.project_request')::uuid),'withdrawn','Restriction withdraws Project pending');
select is((select status from public.resource_listing_requests where id=current_setting('test.mod.resource_request')::uuid),'withdrawn','Restriction withdraws Resource pending');
select is((select status from public.project_join_requests where id=current_setting('test.mod.accepted_project_request')::uuid),'accepted','Other accepted membership is untouched');
select set_config('request.jwt.claim.sub',pg_temp.person(5)::text,true);
select throws_ok($$select public.request_to_join_project(pg_temp.person(5),'fb200000-0000-4000-8000-000000000001')$$,'PT409',null,'Restricted profile cannot request Project');
select throws_ok($$select public.request_resource_listing(pg_temp.person(5),'fb300000-0000-4000-8000-000000000001')$$,'PT409',null,'Restricted profile cannot request Resource');
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
select throws_ok($$select public.accept_project_join_request(pg_temp.person(2),current_setting('test.mod.project_request')::uuid)$$,'PT409',null,'Creator compatibility acceptance checks restricted requester');
select throws_ok($$select public.accept_project_join_request(pg_temp.person(2),current_setting('test.mod.project_request')::uuid,'{}','{}','{}','{}','{}','{}')$$,'PT409',null,'Creator triaged acceptance checks restricted requester');
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
select throws_ok($$select public.accept_project_join_request_as_manager(pg_temp.person(3),current_setting('test.mod.project_request')::uuid)$$,'PT409',null,'Co-creator compatibility checks restricted requester');
select throws_ok($$select public.accept_project_join_request_as_manager(pg_temp.person(3),current_setting('test.mod.project_request')::uuid,'{}','{}','{}','{}','{}','{}')$$,'PT409',null,'Co-creator triaged acceptance checks restricted requester');
select set_config('request.jwt.claim.sub',pg_temp.person(4)::text,true);
select throws_ok($$select public.accept_project_join_request_as_manager(pg_temp.person(4),current_setting('test.mod.project_request')::uuid)$$,'PT409',null,'Co-organizer checks restricted requester');
select throws_ok($$select public.accept_project_join_request_as_manager(pg_temp.person(4),current_setting('test.mod.project_request')::uuid,'{}','{}','{}','{}','{}','{}')$$,'PT409',null,'Co-organizer triaged acceptance checks restricted requester');
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
select public.block_user(pg_temp.person(2),pg_temp.person(5));
select public.unblock_user(pg_temp.person(2),pg_temp.person(5));
select ok(private.profile_has_active_interaction_restriction(pg_temp.person(5)),'Unblock does not revoke restriction');
select public.block_user(pg_temp.person(2),pg_temp.person(5));
select pg_temp.apply('profile',pg_temp.person(3),pg_temp.person(3),'interaction_restriction');
select set_config('request.jwt.claim.sub',pg_temp.person(7)::text,true);
select set_config('test.mod.incoming',public.request_to_join_project(pg_temp.person(7),'fb200000-0000-4000-8000-000000000001')::text,true);
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
select ok(public.accept_project_join_request_as_manager(pg_temp.person(3),current_setting('test.mod.incoming')::uuid) is not null,'Restricted manager accepts eligible incoming requester');
select pg_temp.apply('profile',pg_temp.person(2),pg_temp.person(2),'interaction_restriction');
select set_config('request.jwt.claim.sub',pg_temp.person(9)::text,true);
select set_config('test.mod.creator_incoming',public.request_to_join_project(pg_temp.person(9),'fb200000-0000-4000-8000-000000000001')::text,true);
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
select ok(public.accept_project_join_request(pg_temp.person(2),current_setting('test.mod.creator_incoming')::uuid) is not null,'Restricted Creator accepts eligible incoming requester');
select pg_temp.apply('profile',pg_temp.person(4),pg_temp.person(4),'interaction_restriction');
select set_config('request.jwt.claim.sub',pg_temp.person(11)::text,true);
select set_config('test.mod.organizer_incoming',public.request_to_join_project(pg_temp.person(11),'fb200000-0000-4000-8000-000000000001')::text,true);
select set_config('request.jwt.claim.sub',pg_temp.person(4)::text,true);
select ok(public.accept_project_join_request_as_manager(pg_temp.person(4),current_setting('test.mod.organizer_incoming')::uuid,'{}','{}','{}','{}','{}','{}') is not null,'Restricted Co-organizer triaged acceptance remains available');
select set_config('request.jwt.claim.sub',pg_temp.person(12)::text,true);
select set_config('test.mod.reject_hidden',public.request_to_join_project(pg_temp.person(12),'fb200000-0000-4000-8000-000000000001')::text,true);
select set_config('test.mod.reject_hidden_resource',public.request_resource_listing(pg_temp.person(12),'fb300000-0000-4000-8000-000000000001')::text,true);
select set_config('test.mod.capacity_before',capacity_used_count::text,true) from private.project_registration_capacity_snapshot('fb200000-0000-4000-8000-000000000001');
select set_config('request.jwt.claim.sub',pg_temp.person(8)::text,true);
select set_config('test.mod.hidden_pending',public.request_to_join_project(pg_temp.person(8),'fb200000-0000-4000-8000-000000000001')::text,true);
select set_config('test.mod.hidden_resource_pending',public.request_resource_listing(pg_temp.person(8),'fb300000-0000-4000-8000-000000000001')::text,true);
select set_config('test.mod.hide_project',pg_temp.apply('project',pg_temp.person(2),'fb200000-0000-4000-8000-000000000001','content_hide')::text,true);
select set_config('test.mod.hide_resource',pg_temp.apply('resource_listing',pg_temp.person(2),'fb300000-0000-4000-8000-000000000001','content_hide')::text,true);
select is((select status from public.project_join_requests where id=current_setting('test.mod.hidden_pending')::uuid),'pending','Hide leaves pending Project requests pending');
select is((select status from public.resource_listing_requests where id=current_setting('test.mod.hidden_resource_pending')::uuid),'pending','Hide leaves pending Resource requests pending');
select is((select lifecycle_state from public.proposals where id='fb200000-0000-4000-8000-000000000001'),'published','Hide is orthogonal to Proposal lifecycle');
select is_empty($$select * from public.get_public_proposal('fb200000-0000-4000-8000-000000000001')$$,'Hidden exact Proposal absent');
select is_empty($$select * from public.list_public_proposals() where proposal_id='fb200000-0000-4000-8000-000000000001'$$,'Hidden Proposal list absent');
select is_empty($$select * from public.list_public_project_capacity_statuses(array['fb200000-0000-4000-8000-000000000001']::uuid[])$$,'Hidden public capacity absent');
select is_empty($$select * from public.list_public_project_resource_needs('fb200000-0000-4000-8000-000000000001')$$,'Hidden public Needs absent');
select is_empty($$select * from public.get_public_resource_listing('fb300000-0000-4000-8000-000000000001')$$,'Hidden exact Resource absent');
select is_empty($$select * from public.list_public_resource_listings() where listing_id='fb300000-0000-4000-8000-000000000001'$$,'Hidden Resource list absent');
select ok(not public.can_read_public_cover_image_object(pg_temp.person(2)::text || '/projects/fb200000-0000-4000-8000-000000000001/fb900000-0000-4000-8000-000000000002.webp'),'Hidden Project cover object denied');
select ok(not public.can_read_public_cover_image_object(pg_temp.person(2)::text || '/resources/fb300000-0000-4000-8000-000000000001/fb900000-0000-4000-8000-000000000003.webp'),'Hidden Resource cover object denied');
select set_config('request.jwt.claim.sub',pg_temp.person(10)::text,true);
select is_empty($$select * from public.get_project_creator_profile_photo_for_viewer('fb200000-0000-4000-8000-000000000001')$$,'Hidden Project gives no public photo context');
select is_empty($$select * from public.get_resource_listing_owner_profile_photo_for_viewer('fb300000-0000-4000-8000-000000000001')$$,'Hidden Resource gives no public photo context');
select ok(not public.can_read_public_project_creator_photo_object(pg_temp.person(2)::text || '/fb900000-0000-4000-8000-000000000001.webp'),'Hidden Project contextual photo bytes denied');
select ok(not public.can_read_public_resource_listing_owner_photo_object(pg_temp.person(2)::text || '/fb900000-0000-4000-8000-000000000001.webp'),'Hidden Resource contextual photo bytes denied');
select throws_ok($$select public.request_to_join_project(pg_temp.person(10),'fb200000-0000-4000-8000-000000000001')$$,'PT409',null,'Hidden Project rejects new request');
select throws_ok($$select public.request_resource_listing(pg_temp.person(10),'fb300000-0000-4000-8000-000000000001')$$,'PT409',null,'Hidden Resource rejects new request');
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
select throws_ok($$select public.accept_project_join_request(pg_temp.person(2),current_setting('test.mod.hidden_pending')::uuid)$$,'PT409',null,'Hidden Project blocks Creator accept');
select throws_ok($$select public.accept_resource_listing_request(pg_temp.person(2),current_setting('test.mod.hidden_resource_pending')::uuid)$$,'PT409',null,'Hidden Resource blocks owner accept');
select is((select count(*)::int from public.list_own_moderation_consequences(pg_temp.person(2)) where consequence_type='content_hide'),2,'Immutable Creator/owner sees hides');
select is((select count(*)::int from public.list_own_project_resource_needs(pg_temp.person(2),'fb200000-0000-4000-8000-000000000001')),1,'Restricted Creator retains hidden Needs management read');
select ok(public.reject_resource_listing_request(pg_temp.person(2),current_setting('test.mod.reject_hidden_resource')::uuid) is not null,'Restricted owner may reject hidden Resource pending');
select ok(public.can_manage_cover_image_object(pg_temp.person(2)::text || '/projects/fb200000-0000-4000-8000-000000000001/fb900000-0000-4000-8000-000000000002.webp'),'Creator cover management retained');
select set_config('request.jwt.claim.sub',pg_temp.person(3)::text,true);
select throws_ok($$select public.accept_project_join_request_as_manager(pg_temp.person(3),current_setting('test.mod.hidden_pending')::uuid)$$,'PT409',null,'Hidden Project blocks restricted Co-creator acceptance');
select is((select count(*)::int from public.list_own_moderation_consequences(pg_temp.person(3)) where consequence_type='content_hide'),0,'Co-creator does not get Creator reason');
select is((select count(*)::int from public.get_own_project_shared_workspace(pg_temp.person(3),'fb200000-0000-4000-8000-000000000001')),1,'Hidden Project workspace retained for restricted manager');
select ok(public.reject_project_join_request_as_manager(pg_temp.person(3),current_setting('test.mod.reject_hidden')::uuid) is not null,'Restricted manager may reject hidden Project pending');
select set_config('request.jwt.claim.sub',pg_temp.person(4)::text,true);
select throws_ok($$select public.accept_project_join_request_as_manager(pg_temp.person(4),current_setting('test.mod.hidden_pending')::uuid,'{}','{}','{}','{}','{}','{}')$$,'PT409',null,'Hidden Project blocks Co-organizer triaged accept');
select is((select count(*)::int from public.list_own_moderation_consequences(pg_temp.person(4)) where consequence_type='content_hide'),0,'Co-organizer does not get Creator reason');
select pg_temp.apply('profile',pg_temp.person(6),pg_temp.person(6),'interaction_restriction');
select set_config('request.jwt.claim.sub',pg_temp.person(6)::text,true);
select is((select count(*)::int from public.get_own_project_shared_workspace(pg_temp.person(6),'fb200000-0000-4000-8000-000000000001')),1,'Restricted accepted member retains hidden workspace');
select is((select count(*)::int from public.get_project_participant_meeting_details(pg_temp.person(6),'fb200000-0000-4000-8000-000000000001')),1,'Restricted accepted member retains meeting');
select is((select count(*)::int from public.get_own_project_group_chat(pg_temp.person(6),'fb200000-0000-4000-8000-000000000001')),1,'Restricted accepted member retains group chat');
select ok((select has_current_entitlement from public.get_own_project_group_chat(pg_temp.person(6),'fb200000-0000-4000-8000-000000000001')),'Restricted hidden member retains current chat entitlement');
select lives_ok($$select * from public.list_own_project_membership_commitments(pg_temp.person(6),(select id from public.project_memberships where project_id='fb200000-0000-4000-8000-000000000001' and participant_profile_id=pg_temp.person(6) and left_at is null and removed_at is null))$$,'Restricted hidden member retains commitment read');
select is((select capacity_used_count::text from private.project_registration_capacity_snapshot('fb200000-0000-4000-8000-000000000001')),current_setting('test.mod.capacity_before'),'Hide/restriction do not change capacity occupancy');
select is((select count(*)::int from public.get_resource_exchange_agreement(pg_temp.person(6),current_setting('test.mod.accepted_resource_request')::uuid)),1,'Restricted hidden Resource participant retains agreement');
select lives_ok($$select * from public.submit_moderation_report(pg_temp.person(6),'fb800000-0000-4000-8000-000000000001','other','Synthetic valid evidence remains available','profile',pg_temp.person(10))$$,'Restricted member can submit ordinary evidence');
select is((select status from public.resource_listing_requests where id=current_setting('test.mod.accepted_resource_request')::uuid),'accepted','Restriction and hide preserve accepted Resource');
select ok(private.can_view_profile_photo(pg_temp.person(6),pg_temp.person(2)),'Independent accepted interaction still authorizes owner photo');
select is((select count(*)::int from public.get_profile_photo_for_viewer(pg_temp.person(2))),1,'Independent accepted relationship still returns canonical photo');
update public.profile_photos set audience='public' where profile_id=pg_temp.person(2);
select set_config('request.jwt.claim.sub',pg_temp.person(10)::text,true);
select is((select count(*)::int from public.get_profile_photo_for_viewer(pg_temp.person(2))),1,'Truly public photo remains independently public while content is hidden');
update public.profile_photos set audience='interactions' where profile_id=pg_temp.person(2);
select set_config('request.jwt.claim.sub',pg_temp.person(8)::text,true);
select ok(public.withdraw_project_join_request(pg_temp.person(8),current_setting('test.mod.hidden_pending')::uuid) is not null,'Requester may withdraw hidden Project');
select ok(public.withdraw_resource_listing_request(pg_temp.person(8),current_setting('test.mod.hidden_resource_pending')::uuid) is not null,'Requester may withdraw hidden Resource');
select set_config('request.jwt.claim.sub',pg_temp.person(1)::text,true);
select public.revoke_moderation_consequence(pg_temp.person(1),current_setting('test.mod.restriction')::uuid,'Restored eligibility','Private revoke note');
select is((select status from public.project_join_requests where id=current_setting('test.mod.project_request')::uuid),'withdrawn','Revoke never resurrects requests');
select public.revoke_moderation_consequence(pg_temp.person(1),current_setting('test.mod.hide_project')::uuid,'Restored visibility','Private revoke note');
select is((select count(*)::int from public.get_public_proposal('fb200000-0000-4000-8000-000000000001')),1,'Unhide restores published Proposal');
select set_config('request.jwt.claim.sub',pg_temp.person(5)::text,true);
select throws_ok($$select public.request_to_join_project(pg_temp.person(5),'fb200000-0000-4000-8000-000000000001')$$,'PT409',null,'Restriction revoke does not remove current-manager block');
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
select public.unblock_user(pg_temp.person(2),pg_temp.person(5));
select set_config('request.jwt.claim.sub',pg_temp.person(5)::text,true);
select ok(public.request_to_join_project(pg_temp.person(5),'fb200000-0000-4000-8000-000000000001') is not null,'Revoke restores future eligibility under current rules');
select set_config('request.jwt.claim.sub',pg_temp.person(2)::text,true);
select public.close_resource_listing(pg_temp.person(2),'fb300000-0000-4000-8000-000000000001');
select ok(private.resource_listing_has_active_content_hide('fb300000-0000-4000-8000-000000000001'),'Owner close does not revoke hide');
select set_config('request.jwt.claim.sub',pg_temp.person(1)::text,true);
select public.revoke_moderation_consequence(pg_temp.person(1),current_setting('test.mod.hide_resource')::uuid,'Restored visibility','Private revoke note');
select is_empty($$select * from public.get_public_resource_listing('fb300000-0000-4000-8000-000000000001')$$,'Unhide does not republish closed Resource');
select * from finish();
rollback;
