begin;
select no_plan();
-- Explicit rolled-back MAP05 account gate; legacy assertions remain unchanged.
update private.location_provider_config set enabled=true,daily_units_limit=8000,actor_daily_units=8000;
select is((select enabled from private.location_preview_config),false,'DB disabled');
select is((select daily_credit_limit from private.location_preview_config),0,'Default budget zero');
select ok(not has_function_privilege('anon','public.reserve_location_preview_v1(text,boolean,uuid)','EXECUTE'),'No anonymous meter');
select ok(not has_function_privilege('authenticated','public.finish_location_preview_v1(text,uuid,text)','EXECUTE'),'No client cache write');
select ok(not has_function_privilege('service_role','public.get_location_preview_v1(text,uuid,text,uuid)','EXECUTE'),'Service cannot impersonate protected reads');
select ok(not exists(select 1 from information_schema.role_table_grants where table_name like 'location_preview_%' and grantee in ('anon','authenticated','service_role')),'No raw preview grants');
select throws_ok($$select public.get_public_location_previews_v1('{}')$$,'22023',null,'Nonarray denied');
select throws_ok($$select public.get_public_location_previews_v1((select jsonb_agg(jsonb_build_object('kind','resource','id',gen_random_uuid())) from generate_series(1,51)))$$,'22023',null,'Batch max50');
select throws_ok($$select public.get_public_location_previews_v1('[{"kind":"resource","id":"00000000-0000-4000-8000-000000000001","latitude":45}]')$$,'22023',null,'Caller geography denied');
select is(public.get_public_location_previews_v1('[]'),'[]'::jsonb,'Empty batch valid');
select is(public.reserve_location_preview_v1(repeat('a',64),true,null)->>'status','disabled','Disabled reserves zero');
select is((select count(*) from private.location_preview_usage),0::bigint,'No disabled meter writes');
update private.location_preview_config set enabled=true;
select is(public.reserve_location_preview_v1(repeat('a',64),true,null)->>'status','unconfigured','No license or budget fails closed');
update private.location_preview_config set cache_license_approved=true,daily_credit_limit=4,account_daily_credit_limit=4;
select set_config('test.map03.claim',public.reserve_location_preview_v1(repeat('a',64),true,null)::text,true);
select is(current_setting('test.map03.claim')::jsonb->>'status','ok','Bounded generation reserved');
select is((select used from private.location_preview_usage where scope='credits:global'),4,'Four credits reserved');
select is(public.reserve_location_preview_v1(repeat('a',64),true,null)->>'status','unavailable','Pending deduped');
select is(public.reserve_location_preview_v1(repeat('b',64),false,null)->>'status','budget_exhausted','Hard credit cap');
select lives_ok($$select public.finish_location_preview_v1(repeat('a',64),(current_setting('test.map03.claim')::jsonb->>'token')::uuid,null)$$,'Failed claim stored');
select is(public.reserve_location_preview_v1(repeat('a',64),true,null)->>'status','unavailable','No retry billing for failed claim today');
delete from private.location_preview_images;
delete from private.location_preview_usage;
update private.location_preview_config set daily_credit_limit=100,account_daily_credit_limit=100;
select is(public.reserve_location_preview_v1(repeat('b',64),false,gen_random_uuid())->>'status','ok','Exact reservation permitted');
select is((select count(*) from private.location_preview_images),0::bigint,'Exact never shared cached');
insert into private.location_search_budgets(scope,bucket,used) values('global',date_trunc('day',statement_timestamp() at time zone 'UTC') at time zone 'UTC',96)
 on conflict(scope,bucket) do update set used=96;
select is(public.reserve_location_preview_v1(repeat('c',64),false,gen_random_uuid())->>'status','budget_exhausted','Autocomplete counts against account ceiling');
delete from private.location_search_budgets;
delete from private.location_preview_usage;
select is((select count(*) from generate_series(1,12) n where public.reserve_location_preview_v1(encode(extensions.digest(n::text,'sha256'),'hex'),false,null)->>'status'='ok'),12::bigint,'Twelve anonymous requests');
select is(public.reserve_location_preview_v1(repeat('d',64),false,null)->>'status','rate_limited','Thirteenth anonymous request denied');
delete from private.location_preview_usage;
update private.location_preview_config set daily_credit_limit=2000,account_daily_credit_limit=2000;
select set_config('test.map03.actor',gen_random_uuid()::text,true);
select is((select count(*) from generate_series(1,12) n where public.reserve_location_preview_v1(repeat('f',64),false,current_setting('test.map03.actor')::uuid)->>'status'='ok'),12::bigint,'Actor minute bound');
delete from private.location_preview_usage where scope like 'minute:%';
select is((select count(*) from generate_series(1,8) n where public.reserve_location_preview_v1(repeat('f',64),false,current_setting('test.map03.actor')::uuid)->>'status'='ok'),8::bigint,'Actor reaches 80 credits');
select is(public.reserve_location_preview_v1(repeat('f',64),false,current_setting('test.map03.actor')::uuid)->>'status','budget_exhausted','Actor daily bound');
delete from private.location_preview_config;
select is(public.reserve_location_preview_v1(repeat('e',64),false,null)->>'status','disabled','Missing preview meter closed');
delete from private.location_search_config;
select is(public.reserve_location_preview_v1(repeat('e',64),false,null)->>'status','unconfigured','Missing shared meter closed');
select * from finish();
rollback;
